
macro(CMakeUpdatedFile)
    
    set(${PROJECT_NAME}_m_evacu ${m})
    set(m ${PROJECT_NAME}.CMakeFileGetUpdated)
    cmake_parse_arguments(${m} "READ;WRITE" "FILES" "" ${ARGV})
    list(APPEND ${m}_unsetter ${m}_FILES)
    
    if(${${m}_READ})
        ## set cache 
        list(APPEND ${m}_unsetter ${m}_buf ${m}_is_relative ${m}_buf_files ${m}_buf}.current_ts)
        set(${m}_buf)
        set(${m}_buf_files "${${${m}_FILES}}")

        unset(${${m}_FILES})
        foreach(__var ${${m}_buf_files} )
            cmake_path(IS_ABSOLUTE __var ${m}_is_relative)
            if(NOT ${${m}_is_relative})
                get_filename_component(__var ${__var} ABSOLUTE)
            endif()

            string(REPLACE ":" "" ${m}_buf ${__var})
            string(REPLACE ";" "" ${m}_buf ${${m}_buf})
            file(TIMESTAMP ${__var} ${${m}_buf}.current_ts)
            if(NOT "${${${m}_buf}.cache}" STREQUAL "${${${m}_buf}.current_ts}")
                list(APPEND ${${m}_FILES} ${__var})
            else()
            endif()
        endforeach()
    elseif(${${m}_WRITE})
        foreach(__var ${${${m}_FILES}})
            cmake_path(IS_ABSOLUTE __var ${m}_is_relative)
            if(NOT ${${m}_is_relative})
                get_filename_component(__var ${__var} ABSOLUTE)
            endif()
            string(REPLACE ":" "" ${m}_buf ${__var})
            string(REPLACE ";" "" ${m}_buf ${${m}_buf})
            set(${${m}_buf}.cache ${${${m}_buf}.current_ts} CACHE STRING "CMakeJavac uses." FORCE)
        endforeach()
    else()
        message(FATAL_ERROR "must specify READ | WRITE option")
    endif()
    
    foreach(__var ${${m}_update})
        message("update : ${__var}")
    endforeach()
    
    foreach(__v ${${m}_unsetter})
        unset(${__v})
    endforeach()
    unset(${m}_unsetter)
    set(m ${${PROJECT_NAME}_m_evacu})
endmacro()